### ISSUE TITLE
2.12 community build omnibus ticket

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#203]
- [x] https://github.com/scala/scala/pull/5331 --> add `override` keywords to address failures in https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-
  build/475/console
- [x] Tuple is now final (twitter-util) (upstream: https://github.com/twitter/util/issues/174)
- [ ] fix test failures in macro-paradise follow up for scala/scala#5141 (test failing in `tests/src/test/scala/annotations/run/Kase*scala` annotation tests) /cc @xeno-by 
- [x] fix test compilation error in twitter-util
- [x] re-enable browse (https://github.com/scala/community-builds/pull/301)
- [x] resolve pre-built scala from ivy (https://github.com/adriaanm/community-builds/tree/scala-resolve) to unblock https://github.com/scala/scala/pull/5311
- [x] Add scala-java8-compat (required by Akka)
- [x] Upgrade to ScalaTest 3.0 (required by Akka) (https://github.com/scala/community-builds/issues/269)
- [x] Add Scalactic (dependency of ScalaTest 3.0 & required by Akka)
# submit PRs based on forks (see commit mentions below)
- [ ] macro-paradise (changes to namers)
- [ ] scalatest
- [x] scala-swing (valsiginfer part of scala/scala#5141)
- [x] slick (override -- scala/scala#5331)
- [x] scala-js (override -- scala/scala#5331)
- [x] akka (sam, override -- scala/scala#5331)
- [x] twitter-util (override -- scala/scala#5331)  (upstream: https://github.com/twitter/util/issues/174)

**Comment by adriaanm** [comment]
testing changes at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/477/console

**Comment by adriaanm** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/477/consoleFull:

```
util-core/src/test/java/com/twitter/concurrent/SpoolCompilationTest.java:13:
 <B>$plus$plus(scala.Function0<com.twitter.util.Future<com.twitter.concurrent.Spool<B>>>) 
in com.twitter.concurrent.Spool 
and <B>$plus$plus(scala.Function0<com.twitter.concurrent.Spool<B>>) 
in com.twitter.concurrent.Spool have the same erasure, 
yet neither overrides the other
private static class OwnSpool extends AbstractSpool<String> {
```

**Comment by szeiger** [comment]
Akka has added a dependency on scala-java8-compat in the meantime, so we need to add that to the community build: https://github.com/scala/community-builds/pull/262

**Comment by SethTisue** [comment]
some additional old notes from Adriaan:

> yep -- akka & sbinary are fixed in my forks
> sbt is due to removal of `exit`
> shapeless is junit not seeing default methods
> sbinary is using a -Y option we removed (edited)

**Comment by milessabin** [comment]
If there's anything you'd like me to do wrt shapeless to make your life easier please let me know.

**Comment by SethTisue** [comment]
the only remaining unchecked boxes here were macro-paradise (I opened https://github.com/scala/community-builds/issues/302 on it) and ScalaTest (which is now https://github.com/scala/scala-dev/issues/230)

and there's sbinary, but I'm less concerned about that one. maybe it'll get picked up in a future sweep
