### ISSUE TITLE
trailing commas followup

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dev#299]
TODO:
+ [x] PR an update the spec: scala/scala#5779
+ [x] PR an update the SIP: scala/scala.github.com#731
+ [x] PR scala.meta: scalameta/scalameta#660
+ [x] PR intellij-scala: https://github.com/JetBrains/intellij-scala/commit/1ae11156a96ef29dc1cb03dd7ff927e321dc574f and https://github.com/JetBrains/intellij-scala/commit/6ad57b6775db910ca8b6bd8546a6da7fce43fa48
+ [x] PR scalaparse: lihaoyi/fastparse#145

**Comment by adriaanm** [comment]
Assigned Dale as the coordinator. Multiple people will be involved of course in checking all items off of this list

**Comment by olafurpg** [comment]
For anyone interested, I made a scalafix rewrite to insert missing trailing commas. Here's the diff from running the rewrite on a large corpus https://github.com/olafurpg/scala-repos/pull/19 it's still a WIP, it might be nice to limit the rewrite to varargs (slow, but doable with the new semantic rewrites) or a configured whitelist of term applications such as `List`/`Seq` (fast, doable with syntax only).

**Comment by DavidDudson** [comment]
@olafurpg Does scalafmt have a PR yet?

**Comment by olafurpg** [comment]
Not yet. Scalafmt is still on meta 1.4, will wait for 1.6 which is due next week.

**Comment by dwijnand** [comment]
@SethTisue this is on the top of my out-of-hours TODO list. Lemme know if you need me to fast track it for 2.12.2 and I can try speaking to @eed3si9n.

**Comment by SethTisue** [comment]
Scalariform doesn't even have a 2.12 release at all afaik (https://github.com/scala-ide/scalariform/issues/235), so that one isn't a blocker

presumably the spec and SIP updates will be merged

so perhaps the only pressing thing here is to make sure JetBrains is aware and has this in their pipeline for IntelliJ...?

**Comment by dwijnand** [comment]
Cool. I'm working on that. It's tracked on their end as https://youtrack.jetbrains.com/issue/SCL-10597. Thankfully @jastice might be able to help me with advise and tips.

**Comment by dwijnand** [comment]
It would appear that not only does Scalariform not have a 2.12 release, but Scalariform is at this time dead, looking for new maintainers. So I'm dropping it completely from the checklist.

**Comment by SethTisue** [comment]
(removed from the 2.12.2 milestone since the remaining piece isn't absolutely essential for 2.12.2)

**Comment by dwijnand** [comment]
@Lugzan, of JetBrains, has implemented trailing commas in IntelliJ Scala!

Updated the checklist.
