### ISSUE TITLE
finish the sbt build

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#45]
Let's put this to rest.
## 2.11 vs. 2.12

Might as well do it for 2.11 since it won't be any easier in a 2.12 context and merging it onto 2.12 won't be hard.

On 2.11.x, we should probably leave the ant build around, just for easy testing of suspected regressions. On 2.12.x, we should just delete the ant stuff.
## Tasks (necessary)
- [x] jline
- [x] compare output with ant's (there's a task in the sbt build)
- [x] update `scripts/` directory
  - [x] validate/publish-core
  - [x] validate/test
    - [x] junit
    - [x] partest
    - ~~respect `scalac.args.optimise`~~
    - [x] additional test tasks:
      - [x] port test.osgi
      - [x] port test.bc
      - ~~port test.sbt~~
      - [x] port test.scaladoc
  - [x] integrate/bootstrap
  - [x] integrate/windows
  - [x] minor scripts in tools directory
- [x] Port stability verification to sbt
- [x] community build uses the ant build to build scala
- [x] `integrate/windows` script uses ant
- [x] `integrate/bootstrap` script uses ant
## Tasks (would be nice)
- [x] REPL support (maybe done already? check)
- [x] IntelliJ support out of the box (via custom ScalaInstance support/sbt task to generate project/include project files in root)

**Comment by SethTisue** [comment]
mass of random notes from the team meeting:
- Jason got stuck on JLine/JarJar stuff
  - possible fix: outsource it to a separate project.
    publish a JAR from that project, and pull it into scala/scala.
    (Adriaan has been working on some kind of refactoring making
    it only depend on scala-reflect? I didn't understand this.)
  - JarJar Links doesn't work on Java 8 bytecode
  - we currently use jarjar to also rewrite our own glue code
    that takes JLine. could we instead use a proxy or something?

how about a pure-Java interface to the REPL, with no dependencies,
like the sbt-test-interface?  behind the Java facade we do reflection
or source rewriting or whatever.

Lukas and Jason say they don't use the sbt build yet, but it's mostly
out of habit.  (Lukas doesn't need partest, and junit-only tests are
doable using the IntelliJ build.)

Being able to run the REPL of the Scala that we're building from sbt.
Maybe not strictly necessary; we can still run the REPL using the
script, like we do now. But we need to make sure JLine works in that
case.

Most of the work is moving over the Jenkins stuff and the release build.

There is a test where we diff the ant build products against the sbt
build products. I should keep doing that until we get rid of the ant
build entirely.

What about running the test suite? MiMa? OSGi?

there are some comments in the sbt build file itself with todos,
but there aren't any other writeups or anything like that.

Adriaan: "repl & jline separation -- some ongoing work here:
scala/scala@2.11.x...adriaanm:repflactor-jline-completion"

**Comment by SethTisue** [comment]
a big to-do list of Greg's: https://github.com/gkossakowski/scala/pull/2

the big PR where the build was merged: https://github.com/scala/scala/pull/4455

**Comment by retronym** [comment]
Here's my aborted attempt at incorporating jarjar for repl-jline: https://github.com/scala/scala/pull/4593

**Comment by SethTisue** [comment]
problems running shell scripts (such as `pull-binary-libs.sh`) because of errors like:

    ./tools/binary-repo-lib.sh: line 4: $'\r': command not found

can be resolved as follows: http://superuser.com/a/447651

**Comment by SethTisue** [comment]
several of @szeiger's additional PRs on this have already been merged. he's now working on Jenkins integration (w/ help from @adriaanm and me)

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/4884 is merged, which makes validate-publish-core use sbt, not ant. more scripts needing the same switch:
- [ ] validate/test
  - [ ] find a way to run `partest --srcpath test/scaladoc` (https://github.com/scala/scala-partest-interface/issues/14)
- [ ] integrate/bootstrap
- [ ] integrate/windows
- [ ] minor scripts in tools directory

**Comment by SethTisue** [comment]
@szeiger I can take on the scripts work. validate/test and integrate/windows should be easy-ish. integrate/bootstrap could be harder, but Adriaan and I can work on it together when I'm in SF Feb 8–12

**Comment by szeiger** [comment]
I just checked off some of the remaining tasks. Comparing the output of sbt and ant build can be done with https://github.com/typesafehub/scala-diff, JLine works in the sbt build. I haven't looked at the OSGi tests. They are not yet in the sbt build (unless partest or JUnit can run them).

validate/test should be straight-forward: Add a setup command that sets the Scala bootstrap version to the one from jenkins.properties and run the JUnit and partest tasks.

**Comment by retronym** [comment]
One thing I just noticed is that the `integrate/bootstrap` task will need to be updated to build the module `scala-partest-interface`.

I noticed this as I was using that script to build the modules and partest with my new STARR candidate, then trying to run `partest` through SBT.

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scala-lang.modules#scala-partest-interface_2.12.0-0b29927-nightly;0.5.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      org.scala-lang.modules:scala-partest-interface_2.12.0-0b29927-nightly:0.5.0 (/Users/jason/code/scala/build.sbt#L526)
[warn]        +- org.scala-lang:test:2.12.0-SNAPSHOT
[trace] Stack trace suppressed: run last test/*:update for the full output.
[error] (test/*:update) sbt.ResolveException: unresolved dependency: org.scala-lang.modules#scala-partest-interface_2.12.0-0b29927-nightly;0.5.0: not found
[error] Total time: 16 s, completed 03/02/2016 2:24:18 PM
```

**Comment by retronym** [comment]
Another minor task will be to output to `./build` rather than `./build-sbt`.

The history of using distinct names was to enable a diff of the products of the Ant and SBT builds. But I find the two directories to be inconvenient now for lots of little reasons (I need to edit my `gitignore`-s, my shell aliases that run `build/quick/bin/*` need to be duplicated, and so forth.

IMO, the time is right to default to "build".

**Comment by szeiger** [comment]
@retronym The scala-partest and scala-partest-interface versions in 2.12.x are wrong. Is there still a merge from 2.11.x outstanding?

**Comment by retronym** [comment]
Yes, we need to merge.

**Comment by retronym** [comment]
Here's the merge: https://github.com/scala/scala/pull/4941

**Comment by SethTisue** [comment]
> the time is right to default to "build"

I was planning on doing that as soon as all of the Jenkins jobs no longer used ant. you think it should happen sooner?

**Comment by szeiger** [comment]
It looks like the problem with partest in sbt is really just https://github.com/scala/scala/blob/9fb85af78034c117c46dcd3d2d6e73f6abd081ec/build.sbt#L536. Remove that line and it runs successfully. I tested this on a Windows system that doesn't even have ant installed.

**Comment by SethTisue** [comment]
test.osgi isn't the only test task from the ant build that hasn't been ported yet; there's also test.bc, test.sbt, test.scaladoc. I added more checkboxes up above.

**Comment by szeiger** [comment]
OSGi and scaladoc tests are part of https://github.com/scala/scala/pull/5190.

@adriaanm, do I remember correctly that you wanted `test.sbt` to be dropped?

Regarding `scalac.args.optimise`: Is this actually used in a sensible way? What values can it take? It seems to me that the decision whether to optimize lies with the test script (i.e. `validate/test` always compiles with optimization) and this setting is not really needed.

**Comment by adriaanm** [comment]
yes, we can drop test.sbt in favor of the community build (and hopefully eventually inclusion of API extraction into the compiler)

**Comment by adriaanm** [comment]
i think the `scalac.args.optimise` was an ant-ism (old versions of the build could not use if-then-else...) I think we can assume a closed world in scala/scala now with regards to usage of the build from CI. (That was one of the main goals of this setup, so that we can actually keep cleaning up / evolving our build)

**Comment by adriaanm** [comment]
A lot of this is done, but we're not 100%, so I'm moving this to RC1 for the remainder (release script). It's a bit of a liability to have CI run sbt while the release is cut with ant, so we should close that gap and squish the ant build ASAP once M5 is out.

**Comment by adriaanm** [comment]
mentioning for cross-ref: SI-8379 Decommission the binary-pull and push scripts

**Comment by adriaanm** [comment]
How come the "community build uses ant" task is checked? We haven't switched over yet, right?

**Comment by szeiger** [comment]
@adriaanm You mentioned somewhere that you had made the changes to run the community build on the bootstrapped Scala build

**Comment by adriaanm** [comment]
Yep: https://github.com/adriaanm/community-builds/tree/scala-resolve

**Comment by SethTisue** [comment]
squish!

**Comment by adriaanm** [comment]
poppy-the-bug! 

![chef](http://i.giphy.com/10u6gt11vnm812.gif)
