### ISSUE TITLE
JLine 3: turn Som's old checklist into tickets

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#689]
on [ye olde JLine 3 PR](https://github.com/scala/scala/pull/7645), @som-snytt had this checklist:

- [ ] Backend, nail down interface and protocol
- [ ] ~~Colorization~~ https://github.com/scala/scala-dev/issues/687
- [ ] Excise old continuation handling
- [ ] ~~History and related features~~ https://github.com/scala/scala-dev/issues/690
- [ ] Compile to functions, frontend manages inputs
- [ ] ~~Coursier convenience (I guess this is "magic imports (ivy dependencies etc)" at https://github.com/scala/scala-dev/issues/325)~~
- [ ] Hook up `-x` formatting and contribute to jline
- [ ] ~~Fix // print~~ https://github.com/scala/scala-dev/issues/692
- [ ] ~~Support camel-cased, anagram-style completion as previously~~ https://github.com/scala/scala-dev/issues/691

We need to march down this list and figure out what was already fixed, and for the rest, make tickets here

**Comment by SethTisue** [comment]
None of these _look_ like 2.13.2 blockers to me, but I'd like to know what @som-snytt thinks — Som, can you provide descriptions for these?

**Comment by SethTisue** [comment]
"Coursier convenience", does that refer to pulling in dependencies at runtime? that'd be awesome, but not a blocker of course

UPDATE: I'll assume that, and it's covered under https://github.com/scala/scala-dev/issues/325

**Comment by SethTisue** [comment]
"Excise old continuation handling", finally figured out that "continuation" refers to multiline support. So I guess there's old code related to how we used to do that, that we can delete now that JLine supports it directly

UPDATE: but I found later that `ReplTest` still does it the old way

**Comment by som-snytt** [comment]
You're gonna need a bigger check list.

**Comment by SethTisue** [comment]
> Excise old continuation handling

the old code is causing actual trouble at https://github.com/scala/scala-dev/issues/703

**Comment by SethTisue** [comment]
> the old code is causing actual trouble at #703

false alarm.

I'm going to close this, since nothing further that's obviously actionable has surfaced.
