### ISSUE TITLE
Migrate scala/* repos to GitHub Actions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#785]
we'll still have a one-concurrent-job plan on Travis-CI, so we can still do Scala releases and run a few other jobs

https://app.travis-ci.com/github/scala shows which repos are active

* [x] sbt-scala-module
  * [x] https://github.com/scala/sbt-scala-module/pull/139
  * [x] https://github.com/scala/sbt-scala-module/pull/140
  * [x] https://github.com/scala/sbt-scala-module/releases/tag/v3.0.0
* modules:
  * [x] scala-async: https://github.com/scala/scala-async/pull/274, https://github.com/scala/scala-async/pull/278, https://github.com/scala/scala-async/issues/276
  * [x] scala-parser-combinators: https://github.com/scala/scala-parser-combinators/pull/415, https://github.com/scala/scala-parser-combinators/pull/416, https://github.com/scala/scala-parser-combinators/issues/418
  * [x] scala-parallel-collections: https://github.com/scala/scala-parallel-collections/pull/193, https://github.com/scala/scala-parallel-collections/issues/195
  * [x] scala-java8-compat: https://github.com/scala/scala-java8-compat/pull/242, https://github.com/scala/scala-java8-compat/issues/245
  * [x] scala-xml: https://github.com/scala/scala-xml/pull/564
  * [x] scala-swing: https://github.com/scala/scala-swing/pull/157
  * [x] scala-collection-contrib: https://github.com/scala/scala-collection-contrib/pull/151, https://github.com/scala/scala-collection-contrib/pull/152
  * [x] scala-library-next: https://github.com/scala/scala-library-next/pull/98
  * [x] scala-collection-compat: https://github.com/scala/scala-collection-compat/pull/485 (abandoned), https://github.com/scala/scala-collection-compat/pull/486, https://github.com/scala/scala-collection-compat/pull/487, https://github.com/scala/scala-collection-compat/pull/488
* websites:
  * [x] scala.epfl.ch: Seb says he'll find somebody (https://github.com/scala/scala.epfl.ch/issues/194)
  * [x] scala-lang: https://github.com/scala/scala-lang/pull/1276
  * [x] docs.scala-lang: https://github.com/scala/docs.scala-lang/issues/2176
* other:
  * [ ] scala-rewrites: https://github.com/scala/scala-rewrites/issues/125
* [ ] scala-dist, scala-dist-smoketest, scabot, scala-asm:
  * can we just leave these alone? maybe rotate their secrets?
* [ ] nanotest-strawman: https://github.com/scala/nanotest-strawman/pull/160
* [ ] giter8 templates

**Comment by SethTisue** [comment]
separate ticket on CLA checking: https://github.com/scala/scala-dev/issues/792

**Comment by SethTisue** [comment]
Not all checkboxes are checked, but I think we've done enough. We can do any other migrations as needed.
